


CREATE TABLE tasktype (
    name VARCHAR NOT NULL,
    CONSTRAINT uq_tasktype_name UNIQUE (name)
    );



CREATE TABLE taskstatus (
    name VARCHAR NOT NULL,
    CONSTRAINT uq_taskstatus_name UNIQUE (name)
    );



CREATE TABLE task (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR NOT NULL,
    command VERCHAR NOT NULL,
    callback VERCHAR NOT NULL,
    identifier VARCHAR,
    status VARCHAR DEFAULT 'Queued' NOT NULL,
    activity VARCHAR DEFAULT '' NOT NULL,
    attempts INTEGER DEFAULT 0 NOT NULL,
    users_id INTEGER NOT NULL,
    datetime_created TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp NOT NULL,
    datetime_started TIMESTAMP WITH TIME ZONE,
    datetime_heartbeat TIMESTAMP WITH TIME ZONE,
    datetime_completed TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_task PRIMARY KEY (id),
    CONSTRAINT uq_task_identifier UNIQUE (identifier),
    CONSTRAINT fk_task_type_tasktype FOREIGN KEY (type) REFERENCES tasktype (name),
    CONSTRAINT fk_task_status_taskstatus FOREIGN KEY (status) REFERENCES taskstatus (name),
    CONSTRAINT fk_task_users_id_users FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT ck_task_identifier_not_empty_string CHECK (identifier <> ''),
    CONSTRAINT ck_task_command_not_empty_string CHECK (command <> ''),
    CONSTRAINT ck_task_callback_not_empty_string CHECK (callback <> ''),
    CONSTRAINT ck_task_activity_if_running CHECK ((activity = '') = (status <> 'Running')),
    CONSTRAINT ck_task_identifier_if_running CHECK ((identifier IS NULL) = (status <> 'Running')),
    CONSTRAINT ck_task_datetime_started_if_not_queued CHECK ((datetime_started IS NULL) = (status = 'Queued')),
    CONSTRAINT ck_task_datetime_heartbeat_if_not_queued CHECK ((datetime_heartbeat IS NULL) = (status = 'Queued')),
    CONSTRAINT ck_task_datetime_completed_if_complete CHECK ((datetime_completed IS NOT NULL) = (status IN ('Completed', 'Failed')))
    );



INSERT INTO tasktype (name) VALUES ('Pipeline');
INSERT INTO taskstatus (name) VALUES ('Queued');
INSERT INTO taskstatus (name) VALUES ('Running');
INSERT INTO taskstatus (name) VALUES ('Completed');
INSERT INTO taskstatus (name) VALUES ('Failed');
