


CREATE TABLE bsserver (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    region VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    url VARCHAR NOT NULL,
    CONSTRAINT pk_bsserver PRIMARY KEY (id),
    CONSTRAINT uq_bsserver_region UNIQUE (region),
    CONSTRAINT uq_bsserver_url UNIQUE (url)
    );



CREATE TABLE bsaccount (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bsserver_id INTEGER NOT NULL,
    bsid VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    token VARCHAR NOT NULL,
    CONSTRAINT pk_bsaccount PRIMARY KEY (id),
    CONSTRAINT uq_bsaccount_bsid_bsserver_id UNIQUE (bsid, bsserver_id),
    CONSTRAINT fk_bsaccount_bsserver_id_bsserver FOREIGN KEY(bsserver_id) REFERENCES bsserver (id)
    );
CREATE INDEX ix_bsaccount_bsserver_id on bsaccount (bsserver_id);



CREATE TABLE bsaccount_users (
    users_id INTEGER, --not null as primary key
    bsaccount_id INTEGER,--not null as primary key
    CONSTRAINT pk_bsaccount_users PRIMARY KEY (users_id, bsaccount_id), --index will also be usable for users_id
    CONSTRAINT fk_bsaccount_users_users_id_users FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT fk_bsaccount_users_bsaccount_id_bsaccount FOREIGN KEY (bsaccount_id) REFERENCES bsaccount (id)
    );
CREATE INDEX ix_bsaccount_users_bsaccount_id on bsaccount_users (bsaccount_id);



CREATE TABLE bsrun (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bsserver_id INTEGER NOT NULL, --needed for unique constraint on bsid
    bsid VARCHAR NOT NULL,
    attr JSONB DEFAULT '{}'::jsonb NOT NULL,
    summary JSONB DEFAULT '{}'::jsonb NOT NULL,
    datetime_modified TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_bsrun PRIMARY KEY (id),
    CONSTRAINT uq_bsrun_bsid_bsserver_id UNIQUE (bsserver_id, bsid), --index will also be usable for bsserver_id
    CONSTRAINT fk_bsrun_bsserver_id_bsserver FOREIGN KEY (bsserver_id) REFERENCES bsserver (id)
    );



# a run may be shared and accessible by multiple accounts
CREATE TABLE bsaccount_bsrun (
    bsrun_id INTEGER, --not null as primary key
    bsaccount_id INTEGER,--not null as primary key
    CONSTRAINT pk_bsaccount_bsrun PRIMARY KEY (bsrun_id, bsaccount_id), --index will also be usable for bsrun_id
    CONSTRAINT fk_bsaccount_bsrun_bsrun_id_bsrun FOREIGN KEY (bsrun_id) REFERENCES bsrun (id),
    CONSTRAINT fk_bsaccount_bsrun_bsaccount_id_bsaccount FOREIGN KEY (bsaccount_id) REFERENCES bsaccount (id)
    );
CREATE INDEX ix_bsaccount_bsrun_bsaccount_id on bsaccount_bsrun (bsaccount_id);



CREATE TABLE bsappsession (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    bsserver_id INTEGER NOT NULL, --needed for unique constraint on bsid
    bsrun_id INTEGER NOT NULL, 
    bsid VARCHAR NOT NULL,
    attr JSONB DEFAULT '{}'::jsonb NOT NULL,
    summary JSONB DEFAULT '{}'::jsonb NOT NULL,
    datetime_modified TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_bsappsession PRIMARY KEY (id),
    CONSTRAINT uq_bsappsession_bsid_bsserver_id UNIQUE (bsserver_id, bsid), --index will also be usable for bsserver_id
    CONSTRAINT fk_bsappsession_bsserver_id_bsserver FOREIGN KEY (bsserver_id) REFERENCES bsserver (id),
    CONSTRAINT fk_bsappsession_bsrun_id_bsrun FOREIGN KEY (bsrun_id) REFERENCES bsrun (id)
    );
CREATE INDEX ix_bsappsession_bsrun_id on bsappsession (bsrun_id);



CREATE TABLE bsdataset (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bsserver_id INTEGER NOT NULL, --needed for unique constraint on bsid
    bsappsession_id INTEGER NOT NULL,
    bsid VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    attr JSONB DEFAULT '{}'::jsonb NOT NULL,
    summary JSONB DEFAULT '{}'::jsonb NOT NULL,
    lane INTEGER, --allow null in case lane number ever not available, it is only used to exclude failed lanes
    datetime_modified TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_bsdataset PRIMARY KEY (id),
    CONSTRAINT uq_bsdataset_bsid_bsserver_id UNIQUE (bsserver_id, bsid), --index will also be usable for bsserver_id
    CONSTRAINT fk_bsdataset_bsserver_id_bsserver FOREIGN KEY (bsserver_id) REFERENCES bsserver (id),
    CONSTRAINT fk_bsdataset_bsappsession_id_bsappsession FOREIGN KEY (bsappsession_id) REFERENCES bsappsession (id)
   );
CREATE INDEX ix_bsdataset_bsappsession_id_name on bsdataset (bsappsession_id, lane);
CREATE INDEX ix_bsdataset_lane on bsdataset (name, bsappsession_id);



CREATE TABLE bsexcludedlane (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    bsappsession_id INTEGER NOT NULL,
    lane INTEGER NOT NULL,
    datetime_created TIMESTAMP WITH TIME ZONE NOT NULL,
    users_id INTEGER NOT NULL,
    CONSTRAINT pk_bsexcludedlane PRIMARY KEY (id),
    CONSTRAINT uq_bsexcludedlane_bsappsession_id_lane UNIQUE (bsappsession_id, lane),
    CONSTRAINT fk_bsexcludedlane_bsappsession_id_bsappsession FOREIGN KEY (bsappsession_id) REFERENCES bsappsession (id),
    CONSTRAINT fk_bsexcludedlane_users_id FOREIGN KEY (users_id) REFERENCES users (id)
    );
CREATE INDEX ix_bsexcludedlane_users_id on bsexcludedlane (users_id);



CREATE TABLE bsexcludedsample (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bsappsession_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    datetime_created TIMESTAMP WITH TIME ZONE NOT NULL,
    users_id INTEGER NOT NULL,
    CONSTRAINT pk_bsexcludedsample PRIMARY KEY (id),
    CONSTRAINT uq_bsexcludedsample_bsappsession_id_name UNIQUE (bsappsession_id, name),
    CONSTRAINT fk_bsexcludedsample_bsappsession_id_bsappsession FOREIGN KEY (bsappsession_id) REFERENCES bsappsession (id),
    CONSTRAINT fk_bsexcludedsample_users_id FOREIGN KEY (users_id) REFERENCES users (id)
    );
CREATE INDEX ix_bsexcludedsample_users_id on bsexcludedsample (users_id);



CREATE TABLE bsimportedsample (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bsappsession_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    users_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    datetime_modified TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR NOT NULL,
    CONSTRAINT pk_bsimportedsample PRIMARY KEY (id),
    CONSTRAINT uq_bsimportedsample_bsappsession_id_name UNIQUE (bsappsession_id, name),
    CONSTRAINT fk_bsimportedsample_bsappsession_id_bsappsession FOREIGN KEY (bsappsession_id) REFERENCES bsappsession (id),
    CONSTRAINT fk_bsimportedsample_users_id FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT fk_bsimportedsample_project_id FOREIGN KEY (project_id) REFERENCES project (id)
   );
CREATE INDEX ix_bsimportedsample_users_id on bsimportedsample (users_id);
CREATE INDEX ix_bsimportedsample_project_id on bsimportedsample (project_id);




INSERT INTO bsserver (region, country, url) VALUES ('USE1', 'USA', 'https://api.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('CAC1', 'Canada', 'https://api.cac1.sh.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('EUC1', 'Europe', 'https://api.euc1.sh.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('EUW2', 'UK', 'https://api.euw2.sh.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('CNN1', 'China', 'https://api.cnn1.sh.basespace.illumina.com.cn');
INSERT INTO bsserver (region, country, url) VALUES ('APS2', 'Australia', 'https://api.aps2.sh.basespace.illumina.com');

--DROP TABLE bsimportedsample, bsexcludedsample, bsexcludedlane, bsdataset, bsappsession, bsaccount_bsrun, bsrun, bsaccount_users, bsaccount, bsserver;


