


CREATE TABLE bsserver (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    region VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    url VARCHAR NOT NULL,
    CONSTRAINT pk_bsserver PRIMARY KEY (id),
    CONSTRAINT uq_bsserver_region UNIQUE (region),
    CONSTRAINT uq_bsserver_url UNIQUE (url)
    );



CREATE TABLE bsaccount (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    bsserver_id INTEGER NOT NULL,
    bsid VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    token VARCHAR NOT NULL,
    CONSTRAINT pk_bsaccount PRIMARY KEY (id),
    CONSTRAINT uq_bsaccount_bsid_bsserver_id UNIQUE (bsid, bsserver_id),
    CONSTRAINT fk_bsaccount_bsserver_id_bsserver FOREIGN KEY(bsserver_id) REFERENCES bsserver (id)
    );
CREATE INDEX ix_bsaccount_bsserver_id on bsaccount (bsserver_id);



CREATE TABLE bsaccount_users (
    users_id INTEGER, --not null as primary key
    bsaccount_id INTEGER,--not null as primary key
    CONSTRAINT pk_bsaccount_users PRIMARY KEY (users_id, bsaccount_id), --index will also be usable for users_id
    CONSTRAINT fk_bsaccount_users_users_id_users FOREIGN KEY(users_id) REFERENCES users (id),
    CONSTRAINT fk_bsaccount_users_bsaccount_id_bsaccount FOREIGN KEY(bsaccount_id) REFERENCES bsaccount (id)
    );
CREATE INDEX ix_bsaccount_users_bsaccount_id on bsaccount_users (bsaccount_id);



CREATE TABLE bsrun (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    bsserver_id INTEGER NOT NULL, 
    bsid VARCHAR NOT NULL,
    name VARCHAR NOT NULL, --experimentname
    status VARCHAR NOT NULL,
    attr JSONB DEFAULT '{}'::jsonb NOT NULL,
    datetime_modified TIMESTAMP WITH TIME ZONE,
    datetime_bsmodified TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_bsrun PRIMARY KEY (id),
    CONSTRAINT uq_bsrun_bsid_bsserver_id UNIQUE (bsserver_id, bsid), --index will also be usable for bsserver_id
    CONSTRAINT fk_bsrun_bsserver_id_bsserver FOREIGN KEY(bsserver_id) REFERENCES bsserver (id)
    );



CREATE TABLE bsappsession (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    bsserver_id INTEGER NOT NULL, --needed for unique constraint on bsid
    bsrun_id INTEGER NOT NULL, 
    bsid VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    attr JSONB DEFAULT '{}'::jsonb NOT NULL,
    datetime_modified TIMESTAMP WITH TIME ZONE,
    datetime_bsmodified TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_bsappsession PRIMARY KEY (id),
    CONSTRAINT uq_bsappsession_bsid_bsserver_id UNIQUE (bsserver_id, bsid), --index will also be usable for bsserver_id
    CONSTRAINT fk_bsappsession_bsserver_id_bsserver FOREIGN KEY(bsserver_id) REFERENCES bsserver (id),
    CONSTRAINT fk_bsappsession_bsrun_id_bsrun FOREIGN KEY(bsrun_id) REFERENCES bsrun (id)
    );
CREATE INDEX ix_bsappsession_bsrun_id on bsappsession (bsrun_id);



CREATE TABLE bsdataset (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    bsserver_id INTEGER NOT NULL, --needed for unique constraint on bsid
    bsappsession_id INTEGER NOT NULL, 
    bsid VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    attr JSONB DEFAULT '{}'::jsonb NOT NULL,
    lane INTEGER, --allow null in case lane number ever not available
    datetime_modified TIMESTAMP WITH TIME ZONE,
    datetime_bsmodified TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_bsdataset PRIMARY KEY (id),
    CONSTRAINT uq_bsdataset_bsid_bsserver_id UNIQUE (bsserver_id, bsid), --index will also be usable for bsserver_id
    CONSTRAINT fk_bsdataset_bsserver_id_bsserver FOREIGN KEY(bsserver_id) REFERENCES bsserver (id),
    CONSTRAINT fk_bsdataset_bsappsession_id_bsappsession FOREIGN KEY(bsappsession_id) REFERENCES bsappsession (id)
    );
CREATE INDEX ix_bsdataset_bsappsession_id on bsdataset (bsappsession_id);
CREATE INDEX ix_bsdataset_name on bsdataset (name);
CREATE INDEX ix_bsdataset_lane on bsdataset (lane);



CREATE TABLE bsexcluded_lane (
    bsappsession_id INTEGER, --not null as primary key
    lane INTEGER, --not null as primary key
    datetime_created TIMESTAMP WITH TIME ZONE NOT NULL,
    users_id INTEGER NOT NULL,
    CONSTRAINT pk_bsexcluded_lane_bsappsession_id_lane PRIMARY KEY(bsappsession_id, lane),
    CONSTRAINT fk_bsexcluded_lane_users_id FOREIGN KEY(users_id) REFERENCES users (id)
    );
CREATE INDEX ix_bsexcluded_lane_users_id on bsdataset (users_id);



INSERT INTO bsserver (region, country, url) VALUES ('USE1', 'USA', 'https://api.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('CAC1', 'Canada', 'https://api.cac1.sh.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('EUC1', 'Europe', 'https://api.euc1.sh.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('EUW2', 'UK', 'https://api.euw2.sh.basespace.illumina.com');
INSERT INTO bsserver (region, country, url) VALUES ('CNN1', 'China', 'https://api.cnn1.sh.basespace.illumina.com.cn');
INSERT INTO bsserver (region, country, url) VALUES ('APS2', 'Australia', 'https://api.aps2.sh.basespace.illumina.com');

--DROP TABLE bsexcluded_lane, bsdataset, bsappsession, bsrun, bsaccount_users, bsaccount, bsserver


