


CREATE TABLE IF NOT EXISTS bsserver (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	region VARCHAR NOT NULL, 
	url VARCHAR NOT NULL, 
	CONSTRAINT pk_bsserver PRIMARY KEY (id), 
	CONSTRAINT uq_ bsserver_region UNIQUE (region),
	CONSTRAINT uq_ bsserver_url UNIQUE (url)
    };



CREATE TABLE IF NOT EXISTS bsaccount (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	name VARCHAR NOT NULL, 
	token VARCHAR NOT NULL, 
	bsserver_id INTEGER NOT NULL, 
	CONSTRAINT pk_bsaccounts PRIMARY KEY (id), 
	CONSTRAINT uq_ bsaccounts_name UNIQUE (name)
	CONSTRAINT fk_bsaccount_bsserver_id_bsserver FOREIGN KEY(bsserver_id) REFERENCES bsserver (id),
    );



CREATE TABLE IF NOT EXISTS users_bsaccount (
	users_id INTEGER NOt NULL, 
	bsaccount_id INTEGER NOt NULL, 
	CONSTRAINT uq_ users_bsaccount UNIQUE (users_id, bsaccount_id)
	CONSTRAINT fk_ users_bsaccount_users_id_users FOREIGN KEY(users_id) REFERENCES users (id),
	CONSTRAINT fk_ users_bsaccount_bsaccount_id_bsaccount FOREIGN KEY(bsaccount_id) REFERENCES bsaccount (id),
    );



CREATE TABLE IF NOT EXISTS bsrun (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    
	bsaccount_id INTEGER NOt NULL, 
	CONSTRAINT uq_ users_bsaccount UNIQUE (users_id, bsaccount_id)
	CONSTRAINT fk_ users_bsaccount_users_id_users FOREIGN KEY(users_id) REFERENCES users (id),
	CONSTRAINT fk_ users_bsaccount_bsaccount_id_bsaccount FOREIGN KEY(bsaccount_id) REFERENCES bsaccount (id),
    );



bsruns = Table("bsruns", metadata,
    Column("id", Integer, primary_key=True),
    Column("bsid", Integer, unique=True, nullable=False),
    Column("attr", JSONB, default={}, nullable=False),
    
    Column("num_total", Integer, nullable=True),
    Column("num_uploaded", Integer, nullable=True))



# Yes this is messey but a single run may be shared between multiple accounts.
bsaccounts_bsruns = Table("bsaccounts_bsruns", metadata,
    Column("bsrun_id", Integer, ForeignKey("bsruns.id"), nullable=False),
    Column("bsaccount_id", Integer, ForeignKey("bsaccounts.id"), nullable=False),
    UniqueConstraint("bsrun_id", "bsaccount_id"))



bsappsessions = Table("bsappsessions", metadata,
    Column("id", Integer, primary_key=True),
    Column("bsid", String, unique=True, nullable=False),
    Column("bsrun_id", Integer, ForeignKey("bsruns.id"), nullable=False),
    Column("attr", JSONB, default={}, nullable=False))



bssamples = Table("bssamples", metadata,
    Column("id", Integer, primary_key=True),
    Column("bsappsession_id", Integer, ForeignKey("bsappsessions.id"), nullable=False),
    Column("name", String, nullable=False),
    Column("reads_pf", Integer, nullable=False),
    Column("status", String, default="", nullable=False),
    Column("project_id", Integer, ForeignKey("projects.id"), nullable=True),
    Column("user_id", Integer, ForeignKey("users.id"), nullable=True),
    Column("upload_datetime", DateTime(timezone=True), nullable=True))



bsdatasets = Table("bsdatasets", metadata,
    Column("id", Integer, primary_key=True),
    Column("bsid", String, unique=True, nullable=False),
    Column("bssample_id", Integer, ForeignKey("bssamples.id"), nullable=False),
    Column("attr", JSONB, default={}, nullable=False))



bsprojects = Table("bsprojects", metadata,
    Column("id", Integer, primary_key=True),
    Column("bsid", Integer, unique=True, nullable=False),
    Column("attr", JSONB, default={}, nullable=False),
    
    Column("num_total", Integer, nullable=True),
    Column("num_uploaded", Integer, nullable=True))



# Yes this is messey but a single run may be shared between multiple accounts.
bsaccounts_bsprojects = Table("bsaccounts_bsprojects", metadata,
    Column("bsproject_id", Integer, ForeignKey("bsprojects.id"), nullable=False),
    Column("bsaccount_id", Integer, ForeignKey("bsaccounts.id"), nullable=False),
    UniqueConstraint("bsproject_id", "bsaccount_id"))
